version: '3'

services:
  db:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - eactivos-network
  php:
    build:
      context: ""
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./apps/:/var/www/html/eactivos
    networks:
      - eactivos-network
  nginx:
    build:
      context: ""
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./apps/:/var/www/html/eactivos
    ports:
      - 8080:80
    networks:
      - eactivos-network

volumes:
  db_app:

networks:
  eactivos-network: